name: Generar arte ASCII

on: push

jobs:
    primer_job:
        runs-on: ubuntu-latest
        steps:                    
        - name: add repository file
          uses: actions/checkout@v4

        - name: install cowsay
          run: sudo apt install cowsay -y 

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Esto esta bien loco we, Esta vez si pasa Actions XD" >> pass.txt

        - name: read file
          run: |
            cat pass.txt
            