name: Generar arte ASCII

on: push

jobs:
    primer_job:
        runs-on: ubuntu-latest
        steps:                    
        - name: add repository file
          uses: actions/checkout@v4

        - name: executing shell script
          run: ./ascii-script.sh
            